### ISSUE TITLE
RapidAndroid has stopped unexpectedly

### ISSUE THREAD

**Issue by Edddd** [dimagi/rapidandroid#3]
Hi,

This applications looks great but when I try to configure more than 4 different forms, the application freeze.

Here are some (hopefully) useful extract of the log:

06-02 10:19:08.109 D/AndroidRuntime(4895)Shutting down VM
06-02 10:19:08.109 W/dalvikvm(4895)threadid=3: thread exiting with uncaught exception (group=0x4001b170)
06-02 10:19:08.109 E/AndroidRuntime(4895)Uncaught handler: thread main exiting due to uncaught exception
06-02 10:19:08.116 E/AndroidRuntime(4895)java.lang.RuntimeException: Unable to start activity ComponentInfo{org.rapidandroid/org.rapidandroid.activity.Dashboard}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2496)
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.app.ActivityThread.access$2200(ActivityThread.java:119)
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.os.Handler.dispatchMessage(Handler.java:99)
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.os.Looper.loop(Looper.java:123)
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.app.ActivityThread.main(ActivityThread.java:4363)
06-02 10:19:08.116 E/AndroidRuntime(4895)at java.lang.reflect.Method.invokeNative(Native Method)
06-02 10:19:08.116 E/AndroidRuntime(4895)at java.lang.reflect.Method.invoke(Method.java:521)
06-02 10:19:08.116 E/AndroidRuntime(4895)at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
06-02 10:19:08.116 E/AndroidRuntime(4895)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
06-02 10:19:08.116 E/AndroidRuntime(4895)at dalvik.system.NativeStart.main(Native Method)
06-02 10:19:08.116 E/AndroidRuntime(4895)Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.database.AbstractCursor.checkPosition(AbstractCursor.java:580)
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:214)
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:84)
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.database.CursorWrapper.getInt(CursorWrapper.java:123)
06-02 10:19:08.116 E/AndroidRuntime(4895)at org.rapidandroid.content.translation.ModelTranslator.getFieldsForForm(ModelTranslator.java:330)
06-02 10:19:08.116 E/AndroidRuntime(4895)at org.rapidandroid.content.translation.ModelTranslator.getAllForms(ModelTranslator.java:226)
06-02 10:19:08.116 E/AndroidRuntime(4895)at org.rapidandroid.activity.Dashboard.initFormSpinner(Dashboard.java:641)
06-02 10:19:08.116 E/AndroidRuntime(4895)at org.rapidandroid.activity.Dashboard.onCreate(Dashboard.java:203)
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
06-02 10:19:08.116 E/AndroidRuntime(4895)at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2459)
06-02 10:19:08.116 E/AndroidRuntime(4895)... 11 more
06-02 10:19:08.116 I/Process (1276)Sending signal. PID: 4895 SIG: 3
06-02 10:19:08.132 I/dalvikvm(4895)threadid=7: reacting to signal 3
06-02 10:19:08.132 I/dalvikvm(4895)Wrote stack trace to '/data/anr/traces.txt'
06-02 10:19:10.202 I/Process (4895)Sending signal. PID: 4895 SIG: 9
06-02 10:19:10.226 I/ActivityManager(1276)Process org.rapidandroid (pid 4895) has died.

06-03 15:33:54.253 I/ActivityManager(1276)Starting activity: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.rapidandroid/.activity.Dashboard bnds=[245,58][355,176] }
06-03 15:33:54.285 I/ActivityManager(1276)Start proc org.rapidandroid for activity org.rapidandroid/.activity.Dashboard: pid=4191 uid=10081 gids={3003, 1015}
06-03 15:33:54.480 I/dalvikvm(4191)Debugger thread not active, ignoring DDM send (t=0x41504e4d l=38)
06-03 15:33:54.495 I/dalvikvm(4191)Debugger thread not active, ignoring DDM send (t=0x41504e4d l=36)
06-03 15:33:54.527 I/ActivityThread(4191)Publishing provider org.rapidandroid.provider.RapidSms: org.rapidandroid.content.RapidSmsContentProvider
06-03 15:33:54.738 D/ViewFlipper(1340)updateRunning() mVisible=false, mStarted=true, mUserPresent=true, mRunning=false
06-03 15:33:54.800 D/LocationManager(1325)removeUpdates: listener = com.android.wallpaper.grass.GrassRS$LocationUpdater@44cfff68
06-03 15:33:54.808 D/NetworkLocationProvider(1276)removeListener(): wallpaper
06-03 15:33:54.808 D/NetworkLocationProvider(1276)enableLocationTracking(): false
06-03 15:33:54.870 D/AndroidRuntime(4191)Shutting down VM
06-03 15:33:54.870 W/dalvikvm(4191)threadid=3: thread exiting with uncaught exception (group=0x4001b170)
06-03 15:33:54.870 E/AndroidRuntime(4191)Uncaught handler: thread main exiting due to uncaught exception
06-03 15:33:54.870 E/AndroidRuntime(4191)java.lang.RuntimeException: Unable to start activity ComponentInfo{org.rapidandroid/org.rapidandroid.activity.Dashboard}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2496)
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.app.ActivityThread.access$2200(ActivityThread.java:119)
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.os.Handler.dispatchMessage(Handler.java:99)
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.os.Looper.loop(Looper.java:123)
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.app.ActivityThread.main(ActivityThread.java:4363)
06-03 15:33:54.870 E/AndroidRuntime(4191)at java.lang.reflect.Method.invokeNative(Native Method)
06-03 15:33:54.870 E/AndroidRuntime(4191)at java.lang.reflect.Method.invoke(Method.java:521)
06-03 15:33:54.870 E/AndroidRuntime(4191)at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
06-03 15:33:54.870 E/AndroidRuntime(4191)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
06-03 15:33:54.870 E/AndroidRuntime(4191)at dalvik.system.NativeStart.main(Native Method)
06-03 15:33:54.870 E/AndroidRuntime(4191)Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.database.AbstractCursor.checkPosition(AbstractCursor.java:580)
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:214)
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:84)
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.database.CursorWrapper.getInt(CursorWrapper.java:123)
06-03 15:33:54.870 E/AndroidRuntime(4191)at org.rapidandroid.content.translation.ModelTranslator.getFieldsForForm(ModelTranslator.java:330)
06-03 15:33:54.870 E/AndroidRuntime(4191)at org.rapidandroid.content.translation.ModelTranslator.getAllForms(ModelTranslator.java:226)
06-03 15:33:54.870 E/AndroidRuntime(4191)at org.rapidandroid.activity.Dashboard.initFormSpinner(Dashboard.java:641)
06-03 15:33:54.870 E/AndroidRuntime(4191)at org.rapidandroid.activity.Dashboard.onCreate(Dashboard.java:203)
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
06-03 15:33:54.870 E/AndroidRuntime(4191)at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2459)
06-03 15:33:54.870 E/AndroidRuntime(4191)... 11 more
06-03 15:33:54.878 I/Process (1276)Sending signal. PID: 4191 SIG: 3
06-03 15:33:54.894 I/dalvikvm(4191)threadid=7: reacting to signal 3
06-03 15:33:54.972 I/dalvikvm(4191)Wrote stack trace to '/data/anr/traces.txt'

If I delete the SQLite database, the application restore it and it works well again.

I hope you can help.

Thanks in adavance,
Edouard

**Comment by dmyung** [comment]
Hi Edouard,

Thanks for the information, I'm a bit slammed at the moment on other projects, but will try to take a look into this the next few days.

Other debugging questions:

1:  How/what are the forms constructed from?  Form name? Prefix?  specific field names?

2:  After creating the forms, does it crash when trying to save the 5th form?  And after it crashes, the app is unrecoverable?  

Thanks

Dan

**Comment by Edddd** [comment]
Hi Dan,

The forms are constructed from names and numbers. I can send you the rapidandroid.db if you want.

By the way, I tried to input directly new forms in the sqlite db with SQL instructions (using http://code.google.com/p/sqlite-manager/ ) but was unsuccessful. Great if you have some examples of scripts for that!

After creating the form, the app crash and is unrecoverable.

Thanks for your prompt reaction !
Edouard

**Comment by dmyung** [comment]
Hi,
I was able to create six forms (form name "one", field name (word) "one", form name "two", etc) and I was able to get up to six new forms and it was able to receive messages fine without crashing.  The number of databases shouldn't matter really because all forms (tables) are accessed by name directly, not by sequence, and are just doing direct lookups.    Yeah, please send over the rapidandroid.db if at all possible.   I just sent you a message with my email.

Thanks,
Dan
